# Workflow name and by default it takes to the workflow file path if not given.
name: Sequential Jobs
on: 
    workflow_dispatch:

env:
  message: "Hello World !!!"

jobs:
  
  my-first-job:  # Job identifier #
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        id: STEP1
        run: | 
          echo "${{ env.message }}"         
          echo $SHELL

  my-second-job:  # Job identifier #
    runs-on: windows-latest
    steps:

      - name: Print Windows OS Info
        id: STEP1
        run: systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
      
      - name: Print hostname
        id: STEP1
        run: hostname
        


